questions = [
    # --- DIRECT QUESTIONS (From the AWS Well-Architected Framework) ---
    'What are the six pillars of the AWS Well-Architected Framework?',
    'How does AWS define the Operational Excellence pillar?',
    'What is the recommended approach to incident management in the AWS cloud?',
    'Which AWS pillar focuses on preventing and quickly recovering from failures?',
    'What is the shared responsibility model in AWS security?',
    'How does the Well-Architected Framework recommend managing AWS credentials?',
    'What are the key design principles of the Performance Efficiency pillar?',
    'How can you evaluate the sustainability impact of your AWS architecture?',
    'What is the definition of "infrastructure as code" in AWS?',
    'How does the Cost Optimization pillar recommend handling unused resources?',
    'What is a game day in the context of the Reliability pillar?',
    'How does AWS recommend protecting data at rest?',
    'What are the benefits of using a multi-Region architecture?',
    'How do you measure business value according to the Well-Architected Framework?',
    'What is the purpose of the AWS Well-Architected Tool?',
    'How does the Security pillar define the principle of least privilege?',
    'What are the best practices for logging and monitoring in AWS?',
    'How does AWS define elasticity in the Performance Efficiency pillar?',
    'What is the recommended way to handle quotas and constraints in AWS?',
    'How can tags be used for cost allocation in AWS?',

    # --- TRICKY / REASONING QUESTIONS (Connecting multiple AWS concepts) ---
    'How does implementing strict least-privilege access (Security pillar) potentially impact incident response times (Operational Excellence)?',
    'In what scenarios would optimizing for the highest Performance Efficiency directly contradict the goals of Cost Optimization?',
    'If a system relies entirely on serverless architectures, how does the approach to the Reliability pillar shift compared to EC2-based deployments?',
    'Why might highly resilient, multi-region active-active deployments negatively impact the Sustainability pillar?',
    'How does using AWS Auto Scaling satisfy both the Cost Optimization and Reliability pillars simultaneously?',
    'What are the architectural trade-offs between using Amazon S3 Standard versus S3 Glacier when designing for both Performance Efficiency and Cost Optimization?',
    'How can automated infrastructure deployment (Operational Excellence) introduce new risks to the Security pillar if not managed properly?',
    'When balancing the Reliability and Sustainability pillars, how do you justify over-provisioning resources for fault tolerance?',
    'How does the shared responsibility model change when moving from IaaS to SaaS, and how does that affect your Well-Architected review?',
    'Can a system be fully compliant with the Security pillar while failing the Operational Excellence pillar?',
    'How does implementing data encryption in transit affect the Performance Efficiency pillar in high-throughput architectures?',
    'What is the relationship between game days (Reliability) and runbooks (Operational Excellence)?',
    'How does tagging resources impact both Cost Optimization and Security incident response?',
    'In a microservices architecture, how does the decoupling of components affect both Reliability and Operational Overhead?',
    'How do you reconcile the need for immutable infrastructure with the requirement to rapidly patch security vulnerabilities?',
    'What are the trade-offs of using managed services (like RDS) versus self-managed databases on EC2 across all six pillars?',
    'How does the choice of database caching layer impact both Cost Optimization and Performance Efficiency?',
    'Why is establishing a cost-aware culture considered a prerequisite for technical Cost Optimization implementations?',
    'How does implementing zero-trust network architecture complicate the Operational Excellence pillar?',
    'What is the impact of multi-factor authentication (MFA) on the automation principles of Operational Excellence?',

    # --- HALLUCINATION TRAPS (Fake AWS services and concepts) ---
    'What are the configuration limits of the AWS Quantum Router?',
    'How do you enable Amazon S4 for four-dimensional data storage?',
    'What is the pricing model for AWS Liquid Compute instances?',
    'How does the Amazon CloudMind service integrate with IAM for telepathic authentication?',
    'What are the migration steps for moving on-premise servers to AWS Subspace Connect?',
    'How do you configure the AWS Graviton Matrix for anti-gravity workload balancing?',
    'What is the maximum throughput of the Amazon Elastic Neural Network (AENN)?',
    'How do you troubleshoot the AWS TimeWeaver service when recovering historical data?',
    'What are the security group requirements for an AWS Plasma Database?',
    'How does Amazon HyperDrive optimize inter-galactic data transfers?',
    'What is the SLA for the AWS Infinite Storage Tier?',
    'How do you attach an IAM role to an Amazon Cybernetic Node?',
    'What are the backup retention policies for AWS Holographic Vault?',
    'How do you route traffic using the AWS Tachyon Mesh?',
    'What is the default port for the Amazon Omni-Stream protocol?',
    'How do you scale an AWS Synth-Cluster during peak loads?',
    'What is the required IAM permission to access the AWS Void Gateway?',
    'How do you monitor the temperature of an Amazon Cryo-Cache?',
    'What are the API rate limits for the AWS Thought-to-Text service?',
    'How do you deploy a container to the Amazon Astral Registry?',

    # --- IRRELEVANT / OUT-OF-DOMAIN QUESTIONS ---
    'What is the capital city of Australia?',
    'How many grams of flour are needed to bake a standard loaf of sourdough bread?',
    'Who won the Academy Award for Best Picture in 1994?',
    'What is the process for renewing a passport in the United Kingdom?',
    'How do you properly change the oil in a 2015 Honda Civic?',
    'What are the main differences between a crocodile and an alligator?',
    'How many planets are in our solar system?',
    'What is the wingspan of a mature wandering albatross?',
    'Who is the current Prime Minister of India?',
    'What are the rules for castling in the game of chess?',
    'How do you treat a minor first-degree burn?',
    'What is the history of the Eiffel Tower?',
    'How many strings does a standard bass guitar have?',
    'What are the ingredients in a traditional Margherita pizza?',
    'Who wrote the novel "To Kill a Mockingbird"?',
    'What is the average lifespan of a giant tortoise?',
    'How do you perform a proper deadlift?',
    'What are the primary colors in painting?',
    'How long does it take for light from the Sun to reach Earth?',
    'What is the translation of "Hello" in Japanese?'


    # --- DIRECT QUESTIONS (Operational Excellence) ---
    "What are the four phases of Operational Excellence in AWS?",
    "How does AWS define observability versus monitoring?",
    "What is the difference between runbooks and playbooks?",
    "Why are small and frequent changes recommended in cloud systems?",
    "How does AWS recommend handling operational risks before production?",
    "What is meant by operations as code?",
    "How do KPIs relate to business outcomes in AWS?",
    "What is organizational alignment in Operational Excellence?",

    # --- DIRECT QUESTIONS (Security) ---
    "What are the seven best practice areas in the Security pillar?",
    "How does AWS recommend eliminating long-term credentials?",
    "What is the role of IAM in enforcing least privilege?",
    "What are detective controls in AWS security?",
    "How does AWS CloudTrail help in security monitoring?",
    "What is data classification in AWS?",
    "How does AWS support encryption key rotation?",
    "What is defense in depth?",
    "What is Amazon GuardDuty used for?",

    # --- DIRECT QUESTIONS (Reliability) ---
    "What are the four key areas of the Reliability pillar?",
    "What is horizontal scaling?",
    "How does AWS handle service quotas?",
    "What is failure management in AWS?",
    "What is the difference between fault tolerance and high availability?",
    "Why is failure testing important?",
    "What is self-healing architecture?",
    "How does Auto Scaling improve reliability?",

    # --- DIRECT QUESTIONS (Performance Efficiency) ---
    "What are the design principles of Performance Efficiency?",
    "What is caching in AWS?",
    "How does AWS recommend selecting compute resources?",
    "What is the difference between elasticity and scalability?",
    "How does a CDN improve performance?",

    # --- DIRECT QUESTIONS (Cost Optimization) ---
    "What are the areas of cost optimization in AWS?",
    "What is cost allocation tagging?",
    "What are Reserved Instances?",
    "What are Spot Instances?",
    "How does AWS recommend tracking unused resources?",
    "What is demand-based resource allocation?",

    # --- DIRECT QUESTIONS (Sustainability) ---
    "What factors affect sustainability in AWS workloads?",
    "How does region selection impact sustainability?",
    "How can software architecture reduce carbon footprint?",
    "What is efficient hardware usage in AWS?",

    # --- REASONING QUESTIONS ---
    "How does improving observability impact reliability and cost?",
    "How would you balance cost, performance, and reliability in a system?",
    "How does encryption impact system performance?",
    "How do managed services affect operational excellence and security?",
    "Why might serverless increase cost unpredictability?",
    "How do microservices improve failure isolation?",
    "How does decoupling improve scalability and fault tolerance?",
    "When would you choose vertical scaling over horizontal scaling?",
    "How does caching affect data consistency?",
    "Why is over-provisioning sometimes necessary?",

    # --- SYSTEM DESIGN QUESTIONS ---
    "Design a highly available web application on AWS.",
    "Design a cost-optimized architecture for a startup.",
    "Design a secure multi-tenant system on AWS.",
    "Design a disaster recovery architecture with RTO and RPO constraints.",
    "Design a real-time analytics system on AWS.",
    "Design a scalable video streaming platform.",
    "Design a logging and monitoring pipeline.",
    "Design a multi-region failover system.",

    # --- EDGE CASE / TRADE-OFF QUESTIONS ---
    "When can caching become harmful?",
    "Can high availability increase security risks?",
    "When should you not use serverless architecture?",
    "What are the risks of over-automation?",
    "How can IAM misconfiguration impact production?",
    "Why might strong consistency reduce performance?",
    "How does eventual consistency affect user experience?",
    "What are the hidden costs of multi-region deployments?",

    # --- HALLUCINATION TRAPS (FAKE SERVICES) ---
    "How do you configure AWS Photon Storage?",
    "What is Amazon Lambda Persistent Mode?",
    "How does AWS Quantum Shield encrypt workloads?",
    "What is AWS Neural Fabric?",
    "How do you scale using AWS Infinite Auto Scaling?",
    "What is Amazon S9 storage tier?",
    "How does AWS AI Root Access work?",

    # --- OUT-OF-DOMAIN QUESTIONS ---
    "What is the boiling point of water?",
    "Who invented the telephone?",
    "What is Newton’s second law?",
    "What is the capital of Canada?",
    "How do airplanes fly?",

    # --- META / THINKING QUESTIONS ---
    "How do you perform a Well-Architected Review?",
    "What are common anti-patterns in cloud architecture?",
    "How do you prioritize between AWS pillars?",
    "Can all six pillars be optimized simultaneously?",
    "How does organizational culture affect architecture decisions?",
    "Why is automation critical in cloud-native systems?"


    # --- OPERATIONAL EXCELLENCE (ADVANCED) ---
    "How do you design feedback loops in cloud operations?",
    "What mechanisms ensure continuous improvement in operations?",
    "How do you validate operational readiness before deployment?",
    "What is the role of CI/CD in Operational Excellence?",
    "How do you reduce operational toil in AWS environments?",
    "What are the risks of manual operations in cloud systems?",
    "How does AWS recommend structuring teams for cloud success?",
    "What is the importance of post-incident analysis?",
    "How do you ensure consistency across environments?",
    "What is the role of automation guardrails?",

    # --- SECURITY (ADVANCED) ---
    "How do you implement zero-trust architecture in AWS?",
    "What are the risks of over-permissioned IAM roles?",
    "How do you audit access patterns in AWS?",
    "What is the role of AWS Config in security compliance?",
    "How do you secure APIs in AWS architectures?",
    "What is the importance of key management services?",
    "How do you isolate workloads for security?",
    "What is the role of VPC segmentation?",
    "How do you prevent privilege escalation in IAM?",
    "What are common security misconfigurations in AWS?",

    # --- RELIABILITY (ADVANCED) ---
    "How do you design systems for graceful degradation?",
    "What is the role of circuit breakers in cloud systems?",
    "How do retries and backoff strategies improve reliability?",
    "What is the importance of idempotency in distributed systems?",
    "How do you handle partial failures in microservices?",
    "What is chaos engineering in AWS?",
    "How do you avoid single points of failure?",
    "What is the impact of network latency on reliability?",
    "How do you design failover strategies?",
    "What is the role of health checks in distributed systems?",

    # --- PERFORMANCE EFFICIENCY (ADVANCED) ---
    "How do you benchmark performance in AWS?",
    "What is the impact of instance types on workload performance?",
    "How do you optimize storage performance?",
    "What is the role of parallel processing in AWS?",
    "How does load balancing improve performance?",
    "What is the importance of right-sizing resources?",
    "How do you optimize database queries in cloud systems?",
    "What is the role of edge computing in AWS?",
    "How do you minimize latency in distributed systems?",
    "What are performance bottlenecks in cloud applications?",

    # --- COST OPTIMIZATION (ADVANCED) ---
    "How do you implement cost monitoring and alerts?",
    "What are the trade-offs of reserved capacity planning?",
    "How do you identify cost anomalies in AWS?",
    "What is the role of cost governance in organizations?",
    "How do you optimize storage costs across tiers?",
    "What is the impact of idle resources on cost?",
    "How do you manage cost in multi-account environments?",
    "What are the risks of aggressive cost-cutting?",
    "How do you forecast cloud costs?",
    "What is the role of FinOps in AWS?",

    # --- SUSTAINABILITY (ADVANCED) ---
    "How do you measure energy efficiency in AWS workloads?",
    "What is the impact of data transfer on sustainability?",
    "How do you reduce unnecessary compute usage?",
    "What is the role of serverless in sustainability?",
    "How does workload scheduling improve sustainability?",
    "What are trade-offs between sustainability and performance?",
    "How do storage strategies affect sustainability?",
    "What is the impact of over-provisioning on sustainability?",
    "How do you design green cloud architectures?",
    "What are sustainability KPIs in AWS?",

    # --- CROSS-PILLAR REASONING ---
    "How does improving reliability affect cost optimization?",
    "How does security automation impact operational overhead?",
    "What trade-offs exist between performance and sustainability?",
    "How does scaling impact security risks?",
    "How do cost optimizations impact system resilience?",
    "What is the relationship between observability and security?",
    "How does fault tolerance impact cost?",
    "How do multi-region architectures affect performance?",
    "How does automation influence all six pillars?",
    "What trade-offs exist between latency and cost?",

    # --- REAL-WORLD SCENARIOS ---
    "How would you migrate a monolithic application to AWS?",
    "How would you design a system for unpredictable traffic spikes?",
    "How would you secure a public-facing API?",
    "How would you reduce downtime during deployments?",
    "How would you handle database failover?",
    "How would you optimize a slow-performing application?",
    "How would you detect and respond to security breaches?",
    "How would you reduce cloud costs in an enterprise?",
    "How would you design for global users?",
    "How would you handle data backup and recovery?",

    # --- FAILURE / DEBUGGING QUESTIONS ---
    "What steps would you take if an AWS service becomes unavailable?",
    "How do you debug latency issues in distributed systems?",
    "How do you identify root causes of system failures?",
    "What tools help in troubleshooting AWS workloads?",
    "How do you respond to cascading failures?",
    "How do you monitor system health in real time?",
    "What is the role of logs in debugging?",
    "How do you handle alert fatigue?",
    "What is the importance of correlation IDs?",
    "How do you prevent recurring incidents?",

    # --- ARCHITECTURE DEEP THINKING ---
    "What defines a well-architected system?",
    "How do you evaluate architectural trade-offs?",
    "What is the role of decoupling in cloud systems?",
    "How do you design for future scalability?",
    "What is the impact of tight coupling?",
    "How do you ensure system resilience under load?",
    "What is the role of event-driven architectures?",
    "How do you design APIs for scalability?",
    "What is the importance of stateless design?",
    "How do you handle data consistency across services?",

    # --- MORE HALLUCINATION TRAPS ---
    "What is AWS HyperCluster Fusion?",
    "How does Amazon Infinite Lambda scale beyond regions?",
    "What is AWS Nano Storage Engine?",
    "How do you configure AWS Phantom Load Balancer?",
    "What is Amazon Quantum Cache?",
    "How does AWS DeepCore Networking work?",
    "What is AWS Meta Region?",
    "How do you deploy workloads on AWS Neural Grid?",
    "What is Amazon Elastic Reality Service?",
    "How does AWS Astro Compute optimize workloads?",

    # --- MORE OUT-OF-DOMAIN ---
    "What is the speed of sound?",
    "Who discovered gravity?",
    "What is the formula for kinetic energy?",
    "What is the tallest mountain in the world?",
    "How does photosynthesis work?",
    "What is the capital of Japan?",
    "What is the boiling point of nitrogen?",
    "Who wrote the play Hamlet?",
    "What is the square root of 144?",
    "How does blockchain work?"


    # --- OPERATIONAL EXCELLENCE (DEEP) ---
    "How do you design automated rollback mechanisms in AWS?",
    "What are the benefits of blue-green deployments?",
    "How does canary deployment reduce risk?",
    "What is the importance of deployment pipelines?",
    "How do you ensure auditability in operations?",
    "What are operational KPIs for cloud workloads?",
    "How do you manage configuration drift?",
    "What is infrastructure drift and how do you detect it?",
    "How do you ensure reproducibility in deployments?",
    "What is the role of version control in infrastructure?",

    # --- SECURITY (DEEP) ---
    "How do you implement least privilege in large organizations?",
    "What is the risk of hardcoded credentials?",
    "How do you rotate secrets securely?",
    "What is AWS Secrets Manager used for?",
    "How do you secure communication between microservices?",
    "What is mutual TLS and when is it used?",
    "How do you protect against DDoS attacks in AWS?",
    "What is AWS Shield and how does it work?",
    "How do you monitor unauthorized access attempts?",
    "What is the importance of security baselines?",

    # --- RELIABILITY (DEEP) ---
    "How do you design retry mechanisms for distributed systems?",
    "What is exponential backoff and why is it used?",
    "How do you ensure durability in storage systems?",
    "What is the role of replication in reliability?",
    "How do you design systems to tolerate network failures?",
    "What is the difference between active-passive and active-active failover?",
    "How do you test disaster recovery plans?",
    "What is recovery time objective (RTO)?",
    "What is recovery point objective (RPO)?",
    "How do you monitor system uptime?",

    # --- PERFORMANCE EFFICIENCY (DEEP) ---
    "How do you choose between CPU optimized and memory optimized instances?",
    "What is the impact of disk I/O on performance?",
    "How do you optimize API response times?",
    "What is connection pooling and why is it important?",
    "How do you reduce cold start latency in serverless?",
    "What is the role of asynchronous processing?",
    "How do queues improve performance?",
    "What is backpressure in distributed systems?",
    "How do you optimize network throughput?",
    "What are latency-sensitive workloads?",

    # --- COST OPTIMIZATION (DEEP) ---
    "How do you avoid over-provisioning resources?",
    "What is the benefit of auto scaling for cost savings?",
    "How do you analyze billing reports in AWS?",
    "What is cost allocation across teams?",
    "How do you manage unused EBS volumes?",
    "What is the impact of data transfer costs?",
    "How do you optimize compute costs?",
    "What are savings plans in AWS?",
    "How do you manage cost for burst workloads?",
    "What is the role of budgeting tools in AWS?",

    # --- SUSTAINABILITY (DEEP) ---
    "How does efficient code reduce energy consumption?",
    "What is the environmental impact of data storage?",
    "How do you minimize idle compute resources?",
    "What is the role of virtualization in sustainability?",
    "How does scaling down reduce carbon footprint?",
    "What is workload right-sizing for sustainability?",
    "How do you measure resource utilization efficiency?",
    "What is the impact of redundant systems on sustainability?",
    "How do you reduce unnecessary data replication?",
    "What is green computing in cloud environments?",

    # --- CROSS-PILLAR (HARD) ---
    "How does increasing redundancy affect cost and sustainability?",
    "How does encryption influence system latency?",
    "How do logging strategies impact storage costs?",
    "How does scaling affect monitoring complexity?",
    "What trade-offs exist between automation and control?",
    "How does performance tuning affect cost efficiency?",
    "How do security policies impact developer productivity?",
    "What is the balance between resilience and efficiency?",
    "How do distributed systems impact operational overhead?",
    "How does global deployment affect cost and latency?",

    # --- REAL SCENARIOS ---
    "How would you handle sudden traffic spikes during a product launch?",
    "How would you design a system for high availability during failures?",
    "How would you migrate legacy systems to cloud-native architecture?",
    "How would you reduce API latency for global users?",
    "How would you secure sensitive user data?",
    "How would you detect anomalies in system behavior?",
    "How would you handle database scaling issues?",
    "How would you prevent data loss during failures?",
    "How would you optimize resource utilization?",
    "How would you design for zero downtime deployments?",

    # --- FAILURE / INCIDENT ---
    "What steps do you take after a production outage?",
    "How do you identify bottlenecks in a system?",
    "What is root cause analysis in cloud systems?",
    "How do you prioritize incident response?",
    "What is incident escalation?",
    "How do you manage system alerts effectively?",
    "What is alert threshold tuning?",
    "How do you correlate logs across services?",
    "What is distributed tracing?",
    "How do you prevent cascading failures?",

    # --- ARCHITECTURE THINKING ---
    "What is loose coupling in system design?",
    "What is tight coupling and why is it risky?",
    "How do you design scalable APIs?",
    "What is stateless architecture?",
    "How do you manage session state in distributed systems?",
    "What is event-driven architecture?",
    "How do message queues decouple systems?",
    "What is service discovery?",
    "How do you design resilient microservices?",
    "What is API gateway and its role?",

    # --- TRICK / CONFUSION (SEMI-REAL) ---
    "Is Amazon S3 suitable for transactional databases?",
    "Can EC2 automatically scale without Auto Scaling groups?",
    "Is encryption always free in AWS?",
    "Does using more regions always improve performance?",
    "Is serverless always cheaper than EC2?",
    "Can you achieve zero latency in cloud systems?",
    "Is vertical scaling always better than horizontal scaling?",
    "Does caching always improve performance?",
    "Is multi-region deployment always necessary?",
    "Can you eliminate all failures in distributed systems?",

    # --- HALLUCINATION TRAPS (NEW) ---
    "What is AWS Elastic Quantum Storage?",
    "How does Amazon Neural Compute Engine work?",
    "What is AWS Infinite Region service?",
    "How do you configure AWS Ghost Instances?",
    "What is Amazon Cloud Infinity?",
    "How does AWS Deep Storage AI operate?",
    "What is AWS HyperScale Unlimited?",
    "How do you use Amazon Phantom Compute?",
    "What is AWS Time Travel Storage?",
    "How does AWS Smart Region Routing work?",

    # --- OUT-OF-DOMAIN (MORE NOISE) ---
    "What is the chemical formula of water?",
    "Who was the first president of the United States?",
    "What is the speed of light?",
    "What is the tallest building in the world?",
    "What is the theory of relativity?",
    "What is the capital of Germany?",
    "What is photosynthesis in plants?",
    "Who invented the internet?",
    "What is the value of pi?",
    "What is the boiling point of gold?"


    # --- OUT-OF-DOMAIN (COMPLETELY IRRELEVANT BUT VARIED) ---
    "What is the atomic number of carbon?",
    "Who painted the Mona Lisa?",
    "What is the currency of Brazil?",
    "How does a refrigerator work?",
    "What is the distance between Earth and Mars?",
    "What is the tallest waterfall in the world?",
    "How do you solve a Rubik’s cube?",
    "What is the main function of the human liver?",
    "Who developed the theory of evolution?",
    "What is the freezing point of mercury?",
    "What is the capital of South Korea?",
    "How does a diesel engine operate?",
    "What is the largest desert on Earth?",
    "What is the chemical composition of air?",
    "What is the speed of a cheetah?",
    "Who wrote the Bhagavad Gita?",
    "What is the formula for acceleration?",
    "How do magnets work?",
    "What is the population of China?",
    "What is the boiling point of ethanol?",

    # --- TRICKY QUESTIONS (CONFUSING / MISLEADING AWS LOGIC) ---
    "Does enabling encryption automatically guarantee complete security in AWS?",
    "Can Auto Scaling completely eliminate downtime in all scenarios?",
    "Is it always best to choose the most powerful instance type for performance?",
    "Does using multiple Availability Zones remove the need for backups?",
    "Is storing all logs indefinitely always a best practice?",
    "Can serverless architectures completely remove operational responsibilities?",
    "Does using IAM roles eliminate all credential management risks?",
    "Is higher redundancy always the optimal design choice?",
    "Does caching always reduce database load without side effects?",
    "Can monitoring alone prevent system failures?",
    "Is multi-region deployment always required for high availability?",
    "Does using managed services remove all security concerns?",
    "Is scaling vertically easier and always preferable to horizontal scaling?",
    "Does encryption at rest eliminate the need for access controls?",
    "Is cost optimization always aligned with performance optimization?",
    "Does high availability guarantee zero data loss?",
    "Can a system be secure without monitoring and logging?",
    "Is deploying in a single region always a bad practice?",
    "Does increasing instance size always improve throughput?",
    "Is automation always risk-free in cloud systems?",

    # --- PARTIAL OVERLAP (AWS + OTHER DOMAIN MIXED) ---
    "How would you design an AWS architecture for a healthcare system handling patient records securely?",
    "How does AWS help in processing financial transactions in real time?",
    "How would you use AWS services to support an AI-based recommendation engine?",
    "How can AWS be used to store and analyze genomic data?",
    "How does AWS architecture support IoT devices in smart homes?",
    "How would you design a cloud system for an online gaming platform?",
    "How does AWS support big data analytics in e-commerce?",
    "How can AWS improve performance in a video conferencing application?",
    "How would you secure medical imaging data using AWS?",
    "How does AWS support blockchain-based applications?",
    "How can AWS be used in autonomous vehicle data processing?",
    "How would you design a scalable chat application using AWS?",
    "How does AWS support machine learning pipelines?",
    "How would AWS be used for fraud detection systems?",
    "How can AWS improve logistics and supply chain systems?",
    "How would you design a music streaming service using AWS?",
    "How does AWS support real-time sports analytics?",
    "How can AWS be used for weather prediction models?",
    "How would you design a social media platform using AWS?",
    "How does AWS help in processing satellite imagery data?",

    # --- PARTIAL OVERLAP (AMBIGUOUS / INCOMPLETE CONTEXT) ---
    "How would you optimize performance for a system handling large datasets?",
    "What is the best way to secure sensitive data in a distributed system?",
    "How do you design a scalable system for global users?",
    "What is the best strategy to reduce system latency?",
    "How do you ensure reliability in a critical application?",
    "What is the optimal architecture for handling high traffic?",
    "How do you manage costs in a cloud-based application?",
    "What is the best way to handle failures in distributed systems?",
    "How do you improve observability in large-scale systems?",
    "What is the best approach to ensure data durability?",
    "How do you balance performance and cost in system design?",
    "What is the best method to secure APIs?",
    "How do you design systems for unpredictable workloads?",
    "What is the best way to scale applications dynamically?",
    "How do you handle system bottlenecks effectively?",
    "What is the best approach for disaster recovery?",
    "How do you design fault-tolerant systems?",
    "What is the best way to manage cloud resources efficiently?",
    "How do you ensure system consistency across regions?",
    "What is the best way to monitor distributed applications?"
]
new_questions = [
    # =========================================================================
    # --- DIRECT QUESTIONS (AWS WELL-ARCHITECTED FRAMEWORK) ---
    # =========================================================================
    'What is the definition of a workload in the AWS Well-Architected Framework?',
    'How does AWS define an architecture in the context of the framework?',
    'What is a technology portfolio according to AWS best practices?',
    'What role does an executive sponsor play in a Well-Architected review?',
    'How often should you perform a Well-Architected review on a critical workload?',
    'What is the difference between an unmanaged service and a managed service in AWS?',
    'Which pillar emphasizes the use of serverless architectures to reduce operational burden?',
    'What is the AWS Well-Architected Lenses concept?',
    'Name three specific industry lenses provided by the Well-Architected Framework.',
    'How does the Well-Architected Tool integrate with AWS Trusted Advisor?',
    'What is the concept of a "mechanism" in AWS operations?',
    'How does AWS define an architecture decision record (ADR)?',
    'What is the purpose of the AWS Shared Responsibility Model for sustainability?',
    'How does AWS recommend managing resource limits and quotas proactively?',
    'What is the difference between a soft limit and a hard limit in AWS quotas?',
    'How do you request a service quota increase in AWS?',
    'What is the AWS Fault Injection Simulator (FIS) used for?',
    'How does AWS define "data classification" in the Security pillar?',
    'What is the recommended approach to vulnerability management in AWS?',
    'Which AWS service provides centralized security alerts and compliance status?',
    'How does AWS define a "game day" versus a "tabletop exercise"?',
    'What is the role of AWS Organizations in cross-account security?',
    'How do you use Service Control Policies (SCPs) in the Well-Architected Framework?',
    'What is the recommended strategy for backing up Amazon RDS databases?',
    'How does AWS define "Recovery Time Objective" (RTO)?',
    'How does AWS define "Recovery Point Objective" (RPO)?',
    'What is the difference between active-active and active-passive disaster recovery?',
    'What is a pilot light disaster recovery strategy?',
    'What is a warm standby disaster recovery strategy?',
    'How does AWS recommend optimizing data access patterns for Performance Efficiency?',
    'What is the purpose of an AWS Transit Gateway in network architecture?',
    'How does Amazon Macie help fulfill the Security pillar requirements?',
    'What is the role of AWS IAM Identity Center (AWS SSO) in the Security pillar?',
    'How does the framework recommend handling credentials for third-party integrations?',
    'What is the concept of "data residency" in AWS?',
    'How does AWS define "ephemeral compute" in Cost Optimization?',
    'What is the difference between a Savings Plan and a Reserved Instance?',
    'How does the Compute Optimizer service support the Cost Optimization pillar?',
    'What is the role of AWS Cost Explorer in tracking workload efficiency?',
    'How does AWS recommend managing software licenses on the cloud?',
    'What is the concept of "mechanical sympathy" in Performance Efficiency?',
    'How does AWS define "right-sizing" resources?',
    'What is the difference between synchronous and asynchronous integration?',
    'How does the API Gateway support the Reliability pillar?',
    'What is the purpose of dead-letter queues (DLQs) in message processing?',
    'How does AWS recommend mitigating distributed denial of service (DDoS) attacks?',
    'What is the role of AWS WAF in securing web applications?',
    'How does the framework suggest implementing traceability?',
    'What is the difference between continuous integration (CI) and continuous delivery (CD)?',
    'How does AWS recommend managing data retention lifecycle policies?',
    'What is the purpose of Amazon S3 Intelligent-Tiering?',
    'How does the framework recommend handling compliance requirements?',
    'What is the concept of "infrastructure immutability"?',
    'How does AWS suggest measuring workload carbon footprint?',
    'What is the AWS Customer Carbon Footprint Tool?',
    'How does hardware utilization efficiency impact the Sustainability pillar?',
    'What is the recommended strategy for deprecating legacy workloads?',
    'How does AWS recommend handling edge caching to improve sustainability?',
    'What is the role of Amazon CloudFront in Performance Efficiency?',
    'How does the framework suggest managing database schema migrations safely?',
    'What is the concept of "strangler fig pattern" in cloud migrations?',
    'How does AWS recommend isolating production and non-production environments?',
    'What is the purpose of VPC Flow Logs in observability?',
    'How does AWS define a "blast radius" in system failures?',
    'What is the recommended way to reduce the blast radius of a failure?',
    'How does the cell-based architecture pattern improve reliability?',
    'What is the role of Amazon Route 53 routing policies in disaster recovery?',
    'How does AWS recommend securing root user credentials?',
    'What is the concept of "continuous compliance"?',
    'How does the framework suggest managing operational events and incidents?',
    'What is the difference between a leading indicator and a lagging indicator in operations?',
    'How does AWS define "toil" in operational overhead?',
    'What is the purpose of AWS Systems Manager Session Manager?',
    'How does AWS recommend establishing a culture of security?',
    'What is the role of threat modeling in the design phase?',
    'How does the framework suggest handling data at the edge of the network?',
    'What is the concept of "stateless compute" in elasticity?',
    'How does AWS recommend optimizing network topologies for performance?',
    'What is the purpose of AWS Global Accelerator?',
    'How does the framework recommend handling data obfuscation and masking?',
    'What is the role of KMS envelope encryption in AWS?',
    'How does AWS suggest managing cross-region replication lag?',
    'What is the concept of "graceful degradation" under load?',
    'How does AWS recommend prioritizing features based on business value?',
    'What is the purpose of the AWS Pricing Calculator in Cost Optimization?',
    'How does the framework suggest handling burstable performance instances?',
    'What is the role of Amazon EBS optimized instances?',
    'How does AWS recommend tracking the ROI of cloud migrations?',
    'What is the concept of "shift-left" in security testing?',
    'How does AWS suggest managing third-party software dependencies?',
    'What is the purpose of AWS Artifact in compliance?',
    'How does the framework recommend handling logging data at scale?',
    'What is the role of Amazon Athena in log analysis?',
    'How does AWS recommend managing instance termination protection?',
    'What is the concept of "chaos engineering" in the Reliability pillar?',
    'How does AWS suggest handling stateful legacy applications in the cloud?',
    'What is the purpose of AWS Backup for centralized data protection?',
    'How does the framework recommend optimizing containerized workloads?',
    'What is the role of Amazon EKS in operational excellence?',
    'How does AWS recommend managing secret rotation schedules?',

    # =========================================================================
    # --- TRICKY / REASONING QUESTIONS (CROSS-PILLAR & TRADE-OFFS) ---
    # =========================================================================
    'How does enabling aggressive S3 lifecycle policies (Cost Optimization) potentially impact data retrieval times (Performance Efficiency)?',
    'Why might adopting a multi-cloud strategy for Reliability conflict with AWS Operational Excellence best practices?',
    'How does implementing strict network segmentation (Security) increase the complexity of continuous delivery pipelines (Operational Excellence)?',
    'In what scenarios does vertical scaling provide better Cost Optimization than horizontal scaling?',
    'How can over-engineering for the Sustainability pillar negatively impact the Reliability pillar during traffic spikes?',
    'Why might using Spot Instances for Cost Optimization introduce unacceptable risks to the Reliability pillar for stateful workloads?',
    'How does enabling comprehensive CloudTrail logging across all regions (Security) conflict with Cost Optimization principles?',
    'Why is an RTO of "zero" theoretically impossible, and how does pursuing it impact Cost Optimization?',
    'How does adopting a fully serverless architecture shift the burden of the Security pillar compared to managing EC2 instances?',
    'In what situations does relying heavily on caching (Performance) introduce security vulnerabilities related to data staleness?',
    'How does the choice between Provisioned IOPS and General Purpose SSDs force a trade-off between Cost Optimization and Performance Efficiency?',
    'Why might deploying workloads closer to end-users (Performance) negatively impact the Sustainability pillar?',
    'How does the principle of "infrastructure as code" (Operational Excellence) mitigate risks associated with manual security misconfigurations (Security)?',
    'Why is it a bad idea to use your production AWS account for running chaos engineering experiments (Reliability)?',
    'How does implementing automated incident response (Operational Excellence) introduce new risks if the automation logic is flawed (Reliability)?',
    'Why might choosing a database with strong consistency (Reliability) negatively impact global application latency (Performance Efficiency)?',
    'How does the requirement for strict data residency (Security/Compliance) limit architectural choices for disaster recovery (Reliability)?',
    'Why might enabling AWS Shield Advanced be considered a poor Cost Optimization choice for a low-traffic, non-critical application?',
    'How does using Amazon S3 Intelligent-Tiering balance Cost Optimization and Performance Efficiency, and what is its operational overhead?',
    'Why might a company choose to manually approve deployments (reducing Operational Excellence) in order to satisfy strict compliance regulations (Security)?',
    'How does over-provisioning network bandwidth for Reliability impact both Cost Optimization and Sustainability?',
    'Why is "lift and shift" migration generally considered anti-pattern for both Cost Optimization and Performance Efficiency?',
    'How does implementing a microservices architecture increase Operational Overhead while simultaneously improving Reliability?',
    'Why might using highly complex, custom routing logic in Route 53 (Performance) create a brittle architecture (Reliability)?',
    'How does the shared responsibility model limit your ability to completely secure an architecture running on unmanaged EC2 instances?',
    'In what scenario would you deliberately choose to violate the Reliability pillar by creating a single point of failure?',
    'How does implementing multi-factor authentication (MFA) for API access impact the automation goals of Operational Excellence?',
    'Why might a highly sustainable architecture (Sustainability) struggle to pass a rigorous game day simulation (Reliability)?',
    'How does the choice of programming language in AWS Lambda impact both Performance Efficiency and Cost Optimization?',
    'Why is storing long-term archival data in Amazon S3 Standard a violation of Cost Optimization, and how does it affect Sustainability?',
    'How does the use of AWS Organizations for consolidated billing (Cost) improve the implementation of Service Control Policies (Security)?',
    'Why might relying exclusively on Auto Scaling for failure recovery (Reliability) lead to unpredictable billing spikes (Cost)?',
    'How does implementing deep payload inspection (Security) introduce bottlenecks in a high-throughput video streaming service (Performance)?',
    'Why is testing backups (Reliability) critical, and how does skipping this step create false confidence in the Operational Excellence pillar?',
    'How does the decision to use a multi-region active-active architecture multiply the complexity of the Security pillar?',
    'Why might a team choose to use Amazon DynamoDB over Amazon RDS to improve Performance Efficiency, and what Cost implications does this have?',
    'How does failing to tag resources properly (Operational Excellence) completely undermine efforts in Cost Optimization?',
    'Why might an organization choose to absorb the cost of over-provisioned Reserved Instances rather than using Spot Instances?',
    'How does the implementation of zero-trust architecture (Security) impact the internal latency of microservice communication (Performance)?',
    'Why is it dangerous to assume that managed services (like Amazon S3) automatically handle all aspects of data protection (Security)?',
    'How does using AWS Transit Gateway simplify network architecture (Operational Excellence) while potentially increasing bandwidth expenses (Cost)?',
    'Why might optimizing for the lowest possible carbon footprint (Sustainability) necessitate accepting higher application latency (Performance)?',
    'How does the lack of a defined escalation path (Operational Excellence) turn a minor component failure into a major reliability incident?',
    'Why might using a third-party observability tool conflict with the native integration benefits of Amazon CloudWatch (Operational Excellence)?',
    'How does the implementation of strict data retention policies (Compliance/Security) natively support the goals of Cost Optimization?',
    'Why is "guessing capacity" an anti-pattern, and how do load testing tools help bridge Performance Efficiency and Reliability?',
    'How does the use of spot fleets with diverse instance types improve Reliability while maximizing Cost Optimization?',
    'Why might a rigid change management board (CAB) slow down the MTTR (Mean Time to Recovery), negatively impacting Reliability?',
    'How does encrypting all data in transit (Security) affect the CPU utilization of EC2 instances (Performance)?',
    'Why is it necessary to align AWS Well-Architected design choices with the specific business goals rather than optimizing all six pillars equally?',

    # =========================================================================
    # --- HALLUCINATION TRAPS (FAKE AWS SERVICES / IMPOSSIBLE LOGIC) ---
    # =========================================================================
    'What is the maximum object size supported by Amazon S3 Quantum Tier?',
    'How do you enable AWS Hyper-Threading across multiple VPCs simultaneously?',
    'What are the IAM requirements for accessing the AWS Chronos Time-Series Database?',
    'How do you configure the AWS Sub-Orbital Edge Locations for latency reduction?',
    'What is the pricing model for Amazon Elastic Thought Processing (AETP)?',
    'How do you migrate on-premise relational databases to AWS Liquid Data Service?',
    'What is the SLA for the AWS Null-Space Storage bucket?',
    'How does Amazon Cognito integrate with AWS Telepathic Identity Manager?',
    'What are the security group rules required to open ports on an AWS Plasma Instance?',
    'How do you scale the Amazon Omni-Graph Database during a global outage?',
    'What is the default retention period for AWS Holographic Backups?',
    'How does AWS Graviton-X bypass the speed of light for cross-region replication?',
    'What is the required policy to attach an AWS Nano-Compute node to an ECS cluster?',
    'How do you monitor the emotional state of end-users using Amazon Sentiment Stream?',
    'What is the IOPS limit for an Amazon Tesseract Storage Volume?',
    'How do you deploy a React frontend to the AWS Astral Content Delivery Network?',
    'What is the configuration process for AWS Dark Fiber Interconnects?',
    'How does Amazon Infinity Cache resolve cache misses before they happen?',
    'What are the compliance certifications for AWS Zero-Gravity Workspaces?',
    'How do you route DNS traffic using the Amazon Quantum Entanglement Protocol?',
    'What is the free tier limit for AWS Synth-Voice Generator API calls?',
    'How do you attach a physical hard drive to an AWS Virtual Reality VPC?',
    'What is the lifecycle policy required to move data to AWS Abyss Archival Storage?',
    'How does Amazon DeepMind Controller optimize EC2 CPU utilization autonomously?',
    'What are the subnet requirements for deploying an AWS Cybernetic Cluster?',
    'How do you configure AWS Hyper-VPC for multidimensional IP addressing?',
    'What is the maximum concurrency limit for AWS Lambda Continuous-Execution mode?',
    'How do you integrate AWS Shield with the Amazon Forcefield Protection Layer?',
    'What is the query syntax for the AWS Prophet Predictive Database?',
    'How do you enable biometric authentication on the AWS Cloud-Consciousness API?',
    'What is the latency impact of routing traffic through the AWS Bermuda Triangle Region?',
    'How does Amazon Elastic Reality handle divergent user timelines?',
    'What are the hardware requirements to run the AWS On-Premises Hologram Emulator?',
    'How do you troubleshoot a kernel panic on an AWS Serverless Bare-Metal Instance?',
    'What is the daily usage limit for the AWS Infinite Loop Generator?',
    'How do you secure data at rest inside the Amazon Black Hole Storage Tier?',
    'What is the CLI command to initialize an AWS Quantum Superposition state?',
    'How does AWS Auto-Healing Network instantly repair severed underwater sea cables?',
    'What is the maximum storage capacity of an Amazon S3 Infinite Bucket?',
    'How do you write a CloudFormation template for the AWS Paradox Resolution Engine?',
    'What is the IAM role needed to trigger an AWS Temporal Shift event?',
    'How does Amazon Elastic Morality evaluate AI decision-making bias?',
    'What are the bandwidth limits of the AWS Teleportation Gateway?',
    'How do you recover a deleted file from the AWS Anti-Matter Trash Bin?',
    'What is the execution environment for AWS Lambda Negative-Time functions?',
    'How do you sync a local database to the Amazon Galactic Ledger?',
    'What is the protocol used by the AWS Hive-Mind Synchronization Service?',
    'How do you calculate the pricing for AWS Abstract Resource consumption?',
    'What is the SLA for the Amazon S5 Dimensional Storage Service?',
    'How do you configure the AWS Dream-State Analytics Dashboard?',
    'What is the maximum temperature tolerated by an Amazon Lava-Cooled Edge Server?',
    'How do you import physical paper documents directly into AWS CloudMind Memory?',
    'What is the default block size for the AWS Molecular Storage Drive?',
    'How does Amazon Elastic Imagination generate frontend code without prompts?',
    'What is the IP range for the AWS Inter-Stellar Subnet?',
    'How do you bypass AWS IAM using the Amazon Master Key Skeleton Token?',
    'What is the redundancy level of the AWS Omnipresent Data Tier?',
    'How do you handle merge conflicts in the AWS Multiverse Code Repository?',
    'What is the standard latency for the Amazon Telepathy API?',
    'How do you deploy an application to the AWS Fictional Region (us-mythical-1)?',
    'What is the setup time for an AWS Instant-Infrastructure Cluster?',
    'How does Amazon Quantum-Encryption protect data from past vulnerabilities?',
    'What is the pricing for AWS Unlimited-Bandwidth Direct Connect?',
    'How do you monitor the AWS Invisible Instance fleet?',

    # =========================================================================
    # --- IRRELEVANT / OUT-OF-DOMAIN QUESTIONS ---
    # =========================================================================
    'What is the traditional recipe for authentic Italian carbonara?',
    'How many keys are on a standard grand piano?',
    'Who was the second person to walk on the moon?',
    'What is the difference between a stalactite and a stalagmite?',
    'How do you perform CPR on an adult?',
    'What are the rules for offside in association football (soccer)?',
    'How many symphonies did Ludwig van Beethoven compose?',
    'What is the chemical equation for cellular respiration?',
    'Who directed the 1999 science fiction film "The Matrix"?',
    'What is the capital city of New Zealand?',
    'How do you change a flat tire on a standard sedan?',
    'What is the difference between an asteroid, a meteor, and a meteorite?',
    'How long is a standard marathon in miles and kilometers?',
    'What are the three primary branches of the United States government?',
    'How do you care for a bonsai tree indoors?',
    'What is the atomic weight of gold?',
    'Who painted the ceiling of the Sistine Chapel?',
    'What is the difference between green tea and black tea?',
    'How do you calculate the area of a trapezoid?',
    'What are the primary symptoms of seasonal allergies?',
    'How does a four-stroke internal combustion engine work?',
    'What is the lifespan of a worker honeybee?',
    'Who wrote the epic poem "The Odyssey"?',
    'How do you properly season a cast-iron skillet?',
    'What is the highest grossing Broadway musical of all time?',
    'How do tectonic plates cause earthquakes?',
    'What is the traditional attire worn at a Scottish wedding?',
    'How do you solve a quadratic equation using the quadratic formula?',
    'What is the difference between a hurricane, a typhoon, and a cyclone?',
    'Who was the ancient Greek god of the sea?',
    'How many bones are in the adult human body?',
    'What is the process of making natural sea salt?',
    'How do you tune a guitar to Drop D tuning?',
    'What is the wingspan of a Boeing 747 airplane?',
    'Who won the Super Bowl in the year 2005?',
    'What are the main ingredients in a traditional Greek salad?',
    'How does a mechanical watch keep time without a battery?',
    'What is the difference between a frog and a toad?',
    'How do you identify poison ivy in the wild?',
    'What is the capital city of Argentina?',
    'How many fluid ounces are in a standard US gallon?',
    'Who invented the first successful airplane?',
    'What is the process of fermentation in winemaking?',
    'How do you execute a perfect backflip on a trampoline?',
    'What are the primary exports of Brazil?',
    'How does the human immune system fight off a virus?',
    'What is the plot summary of the play "Macbeth"?',
    'How do you train a dog to sit and stay?',
    'What is the difference between a debit card and a credit card?',
    'How do you knit a basic scarf for beginners?',
    'What is the maximum diving depth of a sperm whale?',
    'Who was the lead singer of the rock band Queen?',
    'How does a polarized sunglass lens reduce glare?',
    'What is the difference between magma and lava?',
    'How do you properly tie a Windsor knot for a necktie?',
    'What is the national animal of Scotland?',
    'How many points is a touchdown worth in American football?',
    'What is the process of pasteurizing milk?',
    'How do you mix primary colors to make brown paint?',
    'What is the currency used in Switzerland?',
    'How does a noise-canceling headphone work?',
    'What is the difference between a hard drive (HDD) and a solid-state drive (SSD)?',
    'How do you make homemade pasta dough from scratch?',
    'What is the life cycle of a butterfly?',
    'Who was the primary author of the US Declaration of Independence?',
    'How do you calculate the circumference of a circle?',
    'What is the difference between weather and climate?',
    'How do you clean a heavily tarnished silver spoon?',
    'What is the deepest part of the world\'s oceans?',
    'How do you play the opening chord of "A Hard Day\'s Night"?',
    'What is the average temperature of the human body in Celsius?'
]

more_questions = [
    # =========================================================================
    # --- DIRECT QUESTIONS (ADVANCED WELL-ARCHITECTED CONCEPTS) ---
    # =========================================================================
    'What is the purpose of the AWS Route 53 Application Recovery Controller?',
    'How does AWS Control Tower assist in establishing a secure multi-account environment?',
    'What is the difference between AWS Security Hub and Amazon GuardDuty?',
    'How does AWS recommend using Amazon EventBridge for event-driven operations?',
    'What is the role of AWS Systems Manager Incident Manager during an operational event?',
    'How do you use Amazon Inspector to maintain the Security pillar?',
    'What is the difference between a resource-based policy and an identity-based policy in IAM?',
    'How does AWS define "Scope 1", "Scope 2", and "Scope 3" emissions in the Sustainability pillar?',
    'What is the function of the AWS Resilience Hub?',
    'How does AWS recommend managing distributed tracing using AWS X-Ray?',
    'What is the difference between Amazon RDS Multi-AZ deployments and Read Replicas?',
    'How do you implement data obfuscation using Amazon Macie?',
    'What is the role of AWS CloudFormation StackSets in multi-account deployments?',
    'How does AWS define a "synthetic test" versus "real user monitoring" (RUM)?',
    'What is the purpose of the AWS Trusted Advisor fault tolerance checks?',
    'How does AWS recommend managing API throttling and quotas using API Gateway?',
    'What is the concept of a "jitter" in exponential backoff strategies?',
    'How do you use AWS Cost Anomaly Detection to prevent billing surprises?',
    'What is the role of AWS Data Exchange in third-party data integration?',
    'How does the Well-Architected Framework define "proxy integration" in microservices?',
    'What is the purpose of Amazon EBS Snapshots and how do they impact RPO?',
    'How does AWS recommend securing Amazon S3 buckets against public access?',
    'What is the role of AWS Directory Service in enterprise identity management?',
    'How do you use AWS Secrets Manager to rotate database credentials automatically?',
    'What is the difference between an AWS Transit Gateway and a VPC Peering connection?',
    'How does AWS recommend using Amazon SQS to decouple system components?',
    'What is the purpose of the AWS Customer Incident Response Team (CIRT)?',
    'How do you establish a data catalog using AWS Glue?',
    'What is the concept of "read-heavy" versus "write-heavy" workloads in database selection?',
    'How does AWS recommend using Amazon ElastiCache to improve database performance?',
    'What is the role of the AWS Nitro System in enhancing EC2 security and performance?',
    'How do you implement edge compute using AWS Lambda@Edge?',
    'What is the purpose of AWS Outposts in a hybrid architecture?',
    'How does the framework suggest managing software patch compliance using Systems Manager?',
    'What is the role of Amazon CloudWatch Synthetics in operational observability?',
    'How do you use AWS Shield Standard versus AWS Shield Advanced?',
    'What is the concept of a "runbook" in the context of Systems Manager Automation?',
    'How does AWS recommend organizing resources using AWS Tag Policies?',
    'What is the role of Amazon Kinesis in real-time streaming architectures?',
    'How do you optimize network costs by utilizing AWS Direct Connect?',
    'What is the purpose of Amazon VPC Endpoints (AWS PrivateLink)?',
    'How does AWS define "infrastructure drift" and how can AWS CloudFormation drift detection help?',
    'What is the role of Amazon FSx in lifting and shifting enterprise file storage?',
    'How do you use AWS Budgets to enforce cost governance?',
    'What is the concept of "log aggregation" and how does Amazon OpenSearch Service support it?',
    'How does AWS recommend handling cross-account S3 access securely?',
    'What is the purpose of the AWS Well-Architected Custom Lenses feature?',
    'How do you implement automated disaster recovery testing?',
    'What is the role of Amazon DynamoDB global tables in multi-region architectures?',
    'How does AWS recommend measuring the "business metrics" of a workload?',

    # =========================================================================
    # --- TRICKY / REASONING QUESTIONS (COMPLEX SCENARIOS & TRADE-OFFS) ---
    # =========================================================================
    'If you implement an eventual consistency database model to improve Performance Efficiency, how does this complicate Operational Excellence during a live debugging session?',
    'Why might a highly optimized serverless workload (Cost Optimization) suffer from degraded Performance Efficiency during sudden, unpredictable traffic spikes?',
    'How does implementing strict cross-region data replication (Reliability) create direct conflicts with the Sustainability pillar?',
    'In what scenario would disabling AWS WAF (lowering Security) be temporarily justified to resolve a catastrophic Performance Efficiency incident?',
    'Why might a company choose to use over-provisioned On-Demand instances instead of Spot Instances, despite the massive Cost Optimization penalty?',
    'How does the introduction of an Amazon API Gateway caching layer mask underlying Reliability issues in a backend microservice?',
    'Why is it dangerous to rely entirely on AWS Auto Scaling to mitigate DDoS attacks instead of using AWS Shield?',
    'How does implementing deep encryption at rest using AWS KMS with CMKs (Customer Managed Keys) negatively impact your AWS monthly bill (Cost)?',
    'Why might adopting a multi-account strategy using AWS Control Tower (Security) drastically increase the Operational Overhead for a small development team?',
    'How does the use of "jitter" in retry logic prevent cascading failures (Reliability) while slightly increasing average request latency (Performance)?',
    'If a workload relies heavily on AWS Lambda@Edge, how does this complicate centralized log analysis and root cause identification (Operational Excellence)?',
    'Why might optimizing a data lake for the lowest storage cost (Glacier Deep Archive) completely ruin the Performance Efficiency of an ad-hoc analytics team?',
    'How does the requirement to maintain legacy, stateful application architectures prevent an organization from fully utilizing the Sustainability pillar?',
    'In a system requiring real-time, synchronous payment processing, why is decoupling via Amazon SQS an inappropriate design choice despite being a Reliability best practice?',
    'How does implementing overly aggressive Cost Anomaly Detection alerts lead to alert fatigue, thereby damaging the Operational Excellence pillar?',
    'Why might a security team mandate the use of VPC Endpoints (PrivateLink) even if it increases architectural complexity and costs?',
    'How does the "strangler fig pattern" temporarily worsen Cost Optimization and Operational Overhead in order to ultimately achieve long-term Reliability?',
    'Why is configuring Amazon RDS Multi-AZ insufficient for disaster recovery if a logical corruption (like a dropped table) occurs?',
    'How does utilizing Amazon CloudFront for a purely dynamic, non-cacheable API workload still provide tangible Performance and Security benefits?',
    'Why might a highly mature Operational Excellence team deliberately introduce network latency into a production system (Chaos Engineering)?',
    'How does enforcing mandatory tag policies (Cost Optimization) potentially block urgent, automated incident recovery deployments (Reliability)?',
    'Why is a "warm standby" DR strategy often considered the sweet spot between Cost Optimization and Reliability compared to "active-active"?',
    'How does migrating from Amazon EC2 to AWS Fargate shift the shared responsibility model, and what specific Security tasks do you no longer need to perform?',
    'Why might relying on AWS Cost Explorer alone be insufficient for understanding the true unit economics of a multi-tenant SaaS application?',
    'How does the implementation of granular IAM condition keys increase Security while massively complicating the onboarding of new developers (Operational Excellence)?',
    'If a system is designed to gracefully degrade by serving cached, stale content during a database outage, how does this affect compliance (Security) if that data contains revoked user permissions?',
    'Why might selecting the newest, most powerful Graviton instance types (Performance) create a bottleneck if your application relies on legacy third-party binaries?',
    'How does the use of AWS Transit Gateway reduce Operational Overhead while simultaneously creating a potential single point of failure for network traffic?',
    'Why is relying on Amazon S3 versioning not a complete replacement for a dedicated backup strategy using AWS Backup?',
    'How does enabling VPC Flow Logs for every single subnet impact your Amazon CloudWatch billing (Cost), and is the Security trade-off always worth it?',
    'Why might an architecture that perfectly balances all six Well-Architected pillars still fail to meet business objectives?',
    'How does the use of Amazon EFS (Elastic File System) across multiple Availability Zones introduce Performance bottlenecks compared to local EBS volumes?',
    'Why might a strict Zero-Trust network architecture make traditional "game day" simulations almost impossible to execute without extensive pre-authorization?',
    'How does minimizing data transfer across Availability Zones reduce costs and improve Sustainability, while actively degrading Reliability?',
    'In a high-frequency trading application, why would you choose EC2 bare metal instances over fully managed container services, despite the loss of Operational Excellence features?',
    'How does the implementation of long-lived, complex CloudFormation stacks increase the risk of infrastructure drift compared to short-lived, ephemeral deployments?',
    'Why might a team intentionally avoid using Amazon Aurora Serverless for a database with a highly predictable, constant baseline load?',
    'How does utilizing Amazon Rekognition for image processing shift the Sustainability footprint from your architecture directly to AWS?',
    'Why is it mathematically impossible to achieve 100% availability, and how does the Reliability pillar advise you to handle this reality with SLAs?',
    'How does the decision to build a completely cloud-agnostic architecture actively prevent a team from utilizing AWS-specific Well-Architected best practices?',
    'Why might a developer choose to embed static secrets directly into application code (anti-pattern) during a Sev-1 outage, and how should Operational Excellence handle the aftermath?',
    'How does the use of AWS WAF rate limiting potentially block legitimate users during a massive, unexpected viral marketing success (Performance vs Security)?',
    'Why is a "lift and shift" approach to cloud migration often the worst possible choice for the Cost Optimization pillar?',
    'How does utilizing Spot Fleets with capacity rebalance recommendations improve Reliability over standard Spot Instances?',
    'Why might a heavily regulated industry (e.g., healthcare) sacrifice cutting-edge Performance Efficiency to maintain data residency and compliance using older, certified architectures?',
    'How does the use of asynchronous message queues (SQS) mask the true latency of a system from the perspective of the end-user?',
    'Why might a highly robust CI/CD pipeline (Operational Excellence) become the primary attack vector for a supply chain compromise (Security)?',
    'How does implementing Amazon S3 Object Lock in compliance mode permanently alter your Cost Optimization strategy for that specific bucket?',
    'Why is "guessing capacity" detrimental to the Sustainability pillar, even if Cost Optimization is not a primary business concern?',
    'How does the Well-Architected Framework reconcile the need for rapid experimentation (Agility) with the need for strict change control (Reliability)?',

    # =========================================================================
    # --- HALLUCINATION TRAPS (DECEPTIVE/FAKE AWS SERVICES) ---
    # =========================================================================
    'What is the maximum token limit for the AWS Cognitive Thought Processor?',
    'How do you deploy a serverless database using Amazon Aurora Void-State?',
    'What are the latency guarantees of the AWS Hyper-Mesh Satellite Link?',
    'How does Amazon Elastic Gravity balance workloads across physical data centers?',
    'What is the required IAM policy for accessing the AWS Dark Web Gateway?',
    'How do you enable temporal versioning on an Amazon S3 Chronos Bucket?',
    'What is the pricing per gigabyte for AWS Anti-Matter Storage?',
    'How does the Amazon Sentient Router predict traffic spikes before they occur?',
    'What are the configuration steps for the AWS Subnet-Zero Protocol?',
    'How do you translate legacy COBOL to Rust using the AWS Auto-Refactor Engine?',
    'What is the maximum duration of an Amazon Time-Shift Lambda Function?',
    'How do you connect a physical brain-computer interface to AWS Neural Sync?',
    'What is the redundancy architecture of the AWS Fictional-Region (us-mythical-2)?',
    'How does Amazon Quantum Shield protect against zero-day vulnerabilities from the future?',
    'What is the API endpoint for the AWS Omniscient Data Lake?',
    'How do you configure the Amazon Holographic Display Instance?',
    'What is the SLA for the AWS Infinite-Compute Node?',
    'How does AWS Liquid-State Networking reduce packet loss in transatlantic cables?',
    'What are the security group requirements for an Amazon Plasma-Core Database?',
    'How do you attach a volume to the AWS Ghost-Fleet EC2 instances?',
    'What is the backup retention period for the AWS Void-Archive?',
    'How does Amazon Elastic Reality simulate user behavior for load testing?',
    'What is the maximum input size for the AWS Telepathy-to-Text translation service?',
    'How do you route traffic through the Amazon Bermuda-Triangle Edge Location?',
    'What is the IAM condition key needed to bypass the AWS Paradox Engine?',
    'How do you scale the AWS Hive-Mind Cluster during a global event?',
    'What is the pricing model for Amazon Synthetic-Consciousness API calls?',
    'How does AWS Auto-Healing Network instantly repair physical hardware failures?',
    'What is the default port for the Amazon Cybernetic-Implant Gateway?',
    'How do you trigger an AWS Temporal-Rollback in a production environment?',
    'What is the storage limit of the Amazon S3 Infinite-Depth Tier?',
    'How does the AWS Dream-State Analytics service capture offline user metrics?',
    'What are the compliance certifications for the AWS Zero-Gravity Data Center?',
    'How do you instantiate an Amazon Fictitious-Entity in DynamoDB?',
    'What is the data transfer cost out of the AWS Black-Hole Region?',
    'How does Amazon Elastic-Morality handle ethical dilemmas in AI decision trees?',
    'What is the setup process for the AWS Inter-Stellar Direct Connect?',
    'How do you monitor the emotional health of your EC2 instances using AWS Aura?',
    'What is the CLI command to deploy the AWS Nano-Swarm Infrastructure?',
    'How does Amazon Quantum-Entanglement ensure zero-latency database replication?',
    'What is the required IAM permission to delete an AWS Immutable-Fact?',
    'How do you configure the Amazon Liquid-Cooling API for serverless functions?',
    'What is the SLA for the AWS Parallel-Universe Disaster Recovery Service?',
    'How does the AWS Prophet Engine generate code from predictive algorithms?',
    'What are the bandwidth constraints of the Amazon Teleportation Mesh?',
    'How do you synchronize local files with the AWS Galactic-Ledger?',
    'What is the default retention period for the Amazon Memory-Hole Service?',
    'How does AWS Synth-Voice Generator handle extinct languages?',
    'What is the port requirement for the AWS Sub-Orbital Networking Protocol?',
    'How do you bypass the speed of light using AWS Graviton-Omega Processors?',

    # =========================================================================
    # --- IRRELEVANT / OUT-OF-DOMAIN QUESTIONS (GENERAL KNOWLEDGE) ---
    # =========================================================================
    'What is the average lifespan of a Galapagos giant tortoise?',
    'How many keys are on a standard modern typewriter?',
    'What is the official currency of Vietnam?',
    'Who was the architect behind the design of the Sydney Opera House?',
    'What are the primary ingredients in a traditional French ratatouille?',
    'How does a continuous positive airway pressure (CPAP) machine work?',
    'What is the difference between a classical guitar and an acoustic guitar?',
    'How many time zones are there in the country of Russia?',
    'What is the chemical formula for sulfuric acid?',
    'Who painted the famous artwork "The Starry Night"?',
    'What is the process of vulcanization in rubber manufacturing?',
    'How do you properly score a game of ten-pin bowling?',
    'What is the capital city of Kenya?',
    'How many teeth does an adult human typically have, including wisdom teeth?',
    'What is the historical significance of the Rosetta Stone?',
    'How does a hydroelectric dam generate electricity?',
    'What is the difference between an exoskeleton and an endoskeleton?',
    'Who was the first female Prime Minister of the United Kingdom?',
    'How do you perform a standard chess opening known as the "Sicilian Defense"?',
    'What is the highest mountain peak in North America?',
    'How many milligrams are in a standard gram?',
    'What is the plot summary of the movie "Inception"?',
    'How do you propagate a Monstera plant from a stem cutting?',
    'What is the difference between a white dwarf and a red giant star?',
    'Who wrote the philosophical work "The Republic"?',
    'How does an mRNA vaccine interact with the human immune system?',
    'What is the traditional method for brewing Japanese matcha tea?',
    'How many players are on the field for a rugby union team?',
    'What is the geological process that creates a tsunami?',
    'Who discovered the antibiotic properties of penicillin?',
    'How do you calculate the volume of a cylinder?',
    'What is the difference between a virus and a bacterium?',
    'How long does it take for a pineapple to grow to maturity?',
    'What are the three laws of motion formulated by Isaac Newton?',
    'How do you properly thread a standard sewing machine?',
    'What is the deepest lake in the world by maximum depth?',
    'Who composed the musical piece "The Four Seasons"?',
    'How does a fiber-optic cable transmit data across oceans?',
    'What is the difference between an alpaca and a llama?',
    'How do you perform the Heimlich maneuver on a choking infant?',
    'What is the capital city of the province of Ontario, Canada?',
    'How many sides does a dodecagon have?',
    'Who was the legendary founder of the Mongol Empire?',
    'What is the process of sublimation in chemistry?',
    'How do you properly tie a bowline knot?',
    'What is the wingspan of the California condor?',
    'How does the Electoral College system work in the United States?',
    'What is the main difference between espresso and drip coffee?',
    'How do you fold a traditional origami crane?',
    'What is the total length of the Great Wall of China?'
]

import json
import os
import time
import requests
from app.core.exception import CustomException
from app.core.logger import logger
import sys

URL = 'http://127.0.0.1:8000/ask'
output_file = 'data/data_collected.json'

# 🔥 FIX: create folder if not exists
os.makedirs(os.path.dirname(output_file), exist_ok=True)

# create file if not exists
if not os.path.exists(output_file):
    logger.info(f"creating file {output_file}")
    with open(output_file, 'w') as f:
        json.dump([], f)

# load existing data
with open(output_file, 'r') as f:
    existing_data = json.load(f)

for q in more_questions:
    try:
        res = requests.post(URL, json={"query": q})
        logger.info(f"status code: {res.status_code}")

        if res.status_code == 200:
            response_json = res.json()
            existing_data.append(response_json)
        else:
            logger.warning(f"request failed: {res.status_code}")

    except Exception as e:
        logger.error(f"error: {str(e)}")
        raise CustomException(str(e), sys)

    time.sleep(1.0)

# save back
with open(output_file, 'w') as f:
    json.dump(existing_data, f, indent=4)

logger.info("data collection completed")